### ISSUE TITLE
FlutterError - Null check operator used on a null value: _ButtonsTabBarState.initState.<fn>

### ISSUE THREAD

**Issue by fauzipadlaw** [afonsocraposo/buttons_tabbar#42]
# Bug Report

## Description

[Provide a clear and concise description of the bug you encountered.]
I got this error in Firebase Crashlytics

## Steps to Reproduce

I do not really not what step to reproduce this issue. This happens on Production release and I see it on Firebase Crashlytics

## Expected Behavior

No errors.

## Actual Behavior

Got error: FlutterError - Null check operator used on a null value: _ButtonsTabBarState.initState.<fn>

## Additional Information

[Provide any additional information that may be helpful in understanding and reproducing the issue.]

` buttons_tabbar: 1.3.7+1`

```
[!] Flutter (Channel stable, 3.10.6, on macOS 13.2 22D49 darwin-arm64, locale en)
    • Flutter version 3.10.6 on channel stable at /Users/efzet/fvm/versions/3.10.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/efzet/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/efzet/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.2.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 116.1.57.53

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by Ibrahim-Chaibedraa** [comment]
I'll take a look at this issue!

**Comment by afonsocraposo** [comment]
Hey @fauzipadlaw !
Without more information about the error specifically or how to reproduce it, I'm afraid it's impossible to figure out this issue.
Can you please provide more information?

**Comment by William0039** [comment]
`final RenderBox tabsParent =
     _tabsParentKey.currentContext?.findRenderObject() as RenderBox;
     final double screenWidth = tabsParent.size.width;

     RenderBox renderBox =
     _tabKeys.first.currentContext?.findRenderObject() as RenderBox;
     double size = renderBox.size.width;
     final double left = (screenWidth - size) / 2;

     renderBox = _tabKeys.last.currentContext?.findRenderObject() as RenderBox;
     size = renderBox.size.width;
     final double right = (screenWidth - size) / 2;
     _centerPadding = EdgeInsets.only(left: left, right: right);
   }` there is a error

**Comment by afonsocraposo** [comment]
@William0039 can you please describe the error?

**Comment by afonsocraposo** [comment]
Closing due to inactivity

**Comment by sinhpn92** [comment]
I have the same issue. @afonsocraposo  This is on `buttons_tabbar: ^1.3.13`.

```
======== Exception caught by scheduler library =====================================================
The following _TypeError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _ButtonsTabBarState._getCenterPadding (package:buttons_tabbar/buttons_tabbar.dart:281:38)
#1      _ButtonsTabBarState.initState.<anonymous closure> (package:buttons_tabbar/buttons_tabbar.dart:193:38)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331:11)
#4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#5      _invoke (dart:ui/hooks.dart:312:13)
#6      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#7      _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```
